name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.1.0
      with:
        # Build's context is the set of files located in the specified PATH or URL
        context: .
        # List of target platforms for build
        platforms: linux/amd64,linux/arm64
        # Push is a shorthand for --output=type=registry
        push: true
        # List of tags
        tags: |
          fanite/aimage:latest
